# Generated by Django 4.2.29 on 2026-05-01 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInboundAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_address', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Eingangs-Adresse',
                'verbose_name_plural': 'Eingangs-Adressen',
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'Aufgelöst'), ('unresolved', 'Nicht aufgelöst')], default='unresolved', max_length=10, verbose_name='Status')),
                ('message_id', models.CharField(max_length=500, unique=True, verbose_name='Message-ID')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Absender')),
                ('recipient_emails', models.TextField(blank=True, default='', verbose_name='Empfänger')),
                ('subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Betreff')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='Text-Body')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='HTML-Body')),
                ('eml_file', models.FileField(blank=True, upload_to='inbound_emails/%Y/%m/', verbose_name='Original .eml')),
                ('received_at', models.DateTimeField(verbose_name='Empfangen am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='accounts.account', verbose_name='Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to=settings.AUTH_USER_MODEL, verbose_name='CRM-Benutzer')),
            ],
            options={
                'verbose_name': 'Eingehende E-Mail',
                'verbose_name_plural': 'Eingehende E-Mails',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/', verbose_name='Datei')),
                ('filename', models.CharField(max_length=300, verbose_name='Dateiname')),
                ('content_type', models.CharField(max_length=200, verbose_name='MIME-Typ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.inboundemail', verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'E-Mail-Anhang',
                'verbose_name_plural': 'E-Mail-Anhänge',
            },
        ),
        migrations.CreateModel(
            name='UserEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benutzer-E-Mail-Adresse',
                'verbose_name_plural': 'Benutzer-E-Mail-Adressen',
                'unique_together': {('user', 'email')},
            },
        ),
    ]
