# Generated by Django 4.2.29 on 2026-05-01 09:47

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('verwalter', 'Verwalter')], default='verwalter', max_length=20)),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CustomCRM', help_text='Name des Systems, wird in der Navigation und im Titel angezeigt', max_length=100, verbose_name='Systemname')),
                ('logo', models.ImageField(blank=True, help_text='Logo im PNG-Format (rechteckig empfohlen, max. 200px Höhe)', null=True, upload_to='branding/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#CED51E', help_text='Hauptfarbe im Hex-Format (z.B. #CED51E)', max_length=7, verbose_name='Primärfarbe')),
                ('account_label_singular', models.CharField(default='Konto', help_text='z.B. "Kommune", "Organisation", "Kunde"', max_length=50, verbose_name='Account-Bezeichnung (Einzahl)')),
                ('account_label_plural', models.CharField(default='Konten', help_text='z.B. "Kommunen", "Organisationen", "Kunden"', max_length=50, verbose_name='Account-Bezeichnung (Mehrzahl)')),
                ('product_label_singular', models.CharField(default='Produkt', help_text='z.B. "Produkt", "Service", "Leistung"', max_length=50, verbose_name='Produkt-Bezeichnung (Einzahl)')),
                ('product_label_plural', models.CharField(default='Produkte', help_text='z.B. "Produkte", "Services", "Leistungen"', max_length=50, verbose_name='Produkt-Bezeichnung (Mehrzahl)')),
                ('contact_label_singular', models.CharField(default='Kontakt', max_length=50, verbose_name='Kontakt-Bezeichnung (Einzahl)')),
                ('contact_label_plural', models.CharField(default='Kontakte', max_length=50, verbose_name='Kontakt-Bezeichnung (Mehrzahl)')),
                ('contracts_enabled', models.BooleanField(default=True, help_text='Wenn deaktiviert, werden Vertrags-Menüpunkte und -Widgets ausgeblendet', verbose_name='Verträge aktiviert')),
                ('campaigns_enabled', models.BooleanField(default=True, help_text='Wenn deaktiviert, werden Kampagnen-Menüpunkte ausgeblendet', verbose_name='Kampagnen aktiviert')),
            ],
            options={
                'verbose_name': 'Systemeinstellungen',
                'verbose_name_plural': 'Systemeinstellungen',
            },
        ),
    ]
