# Generated by Django 6.0.1 on 2026-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CustomCRM', help_text='Name des Systems, wird in der Navigation und im Titel angezeigt', max_length=100, verbose_name='Systemname')),
                ('logo', models.ImageField(blank=True, help_text='Logo im PNG-Format (rechteckig empfohlen, max. 200px Höhe)', null=True, upload_to='branding/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#CED51E', help_text='Hauptfarbe im Hex-Format (z.B. #CED51E)', max_length=7, verbose_name='Primärfarbe')),
            ],
            options={
                'verbose_name': 'Systemeinstellungen',
                'verbose_name_plural': 'Systemeinstellungen',
            },
        ),
    ]
