# Generated by Django 6.0.2 on 2026-02-05 11:22

import django.db.models.deletion
from django.db import migrations, models


def set_integreat_as_default(apps, schema_editor):
    """Set Integreat as default dashboard product for all existing users."""
    CustomUser = apps.get_model('core', 'CustomUser')
    Product = apps.get_model('products', 'Product')
    try:
        integreat = Product.objects.get(name='Integreat')
        CustomUser.objects.filter(default_dashboard_product__isnull=True).update(
            default_dashboard_product=integreat
        )
    except Product.DoesNotExist:
        pass  # Integreat product doesn't exist, skip


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_settings'),
        ('products', '0006_add_accountproduct_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_dashboard_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='products.product', verbose_name='Standard-Dashboard-Produkt'),
        ),
        migrations.RunPython(set_integreat_as_default, migrations.RunPython.noop),
    ]
