# Generated by Django 6.0.2 on 2026-02-09 19:56

from django.db import migrations, models


def rename_superadmin_role(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    CustomUser.objects.filter(role='superadmin').update(role='superuser')


def rename_superuser_role(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    CustomUser.objects.filter(role='superuser').update(role='superadmin')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_default_dashboard_product'),
    ]

    operations = [
        migrations.RunPython(rename_superadmin_role, rename_superuser_role),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('verwalter', 'Verwalter')], default='verwalter', max_length=20),
        ),
    ]
