# Generated by Django 6.0.1 on 2026-01-30 13:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
            ],
            options={
                'verbose_name': 'Vertragstyp',
                'verbose_name_plural': 'Vertragstypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_annual_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bruttojahrespreis (€)')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Laufzeit (Monate)')),
                ('is_self_cancelling', models.BooleanField(default=False, verbose_name='Selbstkündigend')),
                ('renewal_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verlängerungsintervall (Monate)')),
                ('notice_period_months', models.PositiveIntegerField(default=3, verbose_name='Kündigungsfrist (Monate)')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.account', verbose_name='Account')),
                ('account_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='products.accountproduct', verbose_name='Account-Produkt')),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contracts.contracttype', verbose_name='Vertragstyp')),
            ],
            options={
                'verbose_name': 'Vertrag',
                'verbose_name_plural': 'Verträge',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contract_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF-Datei')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='Vertrag')),
            ],
            options={
                'verbose_name': 'Vertragsdokument',
                'verbose_name_plural': 'Vertragsdokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
