# Generated by Django 6.0.2 on 2026-02-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_self_cancelling',
            field=models.BooleanField(default=False, verbose_name='Keine automatische Verlängerung'),
        ),
    ]
