# Generated by Django 6.0.2 on 2026-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_is_self_cancelling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_self_cancelling',
            field=models.BooleanField(default=False, verbose_name='Festes Enddatum'),
        ),
    ]
