# Generated by Django 6.0.2 on 2026-02-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rename_is_self_cancelling_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
