# Generated by Django 6.0.1 on 2026-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('bundesland', models.CharField(blank=True, choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thüringen')], max_length=2, verbose_name='Bundesland')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
            ],
            options={
                'verbose_name': 'Account-Typ',
                'verbose_name_plural': 'Account-Typen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Männlich'), ('w', 'Weiblich'), ('d', 'Divers')], max_length=1, verbose_name='Geschlecht')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Position')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptansprechpartner')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
