# Generated by Django 4.2.29 on 2026-05-01 09:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notizen')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
            ],
            options={
                'verbose_name': 'Account-Typ',
                'verbose_name_plural': 'Account-Typen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Telefonanruf'), ('email', 'E-Mail'), ('meeting', 'Termin'), ('task', 'Aufgabe')], max_length=10, verbose_name='Typ')),
                ('subject', models.CharField(max_length=300, verbose_name='Betreff')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('date', models.DateTimeField(verbose_name='Datum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aktivität',
                'verbose_name_plural': 'Aktivitäten',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Männlich'), ('w', 'Weiblich'), ('d', 'Divers')], max_length=1, verbose_name='Geschlecht')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Position')),
                ('anrede', models.CharField(blank=True, default='', max_length=200, verbose_name='Anrede')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptansprechperson')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeitsdatum')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='todo_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF-Anhang')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='accounts.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
