# Generated by Django 6.0.1 on 2026-02-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_todo_attachment'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='inbound_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='emails.inboundemail', verbose_name='Eingehende E-Mail'),
        ),
    ]
