# Generated by Django 6.0.1 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activity_inbound_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung'),
        ),
    ]
