# Generated by Django 6.0.2 on 2026-02-27 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_task_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Jahr')),
                ('satisfaction_app', models.IntegerField(blank=True, null=True, verbose_name='App')),
                ('satisfaction_cms', models.IntegerField(blank=True, null=True, verbose_name='Redaktionssystem')),
                ('satisfaction_support', models.IntegerField(blank=True, null=True, verbose_name='Betreuung')),
                ('satisfaction_overall', models.IntegerField(blank=True, null=True, verbose_name='Gesamt')),
                ('satisfaction_content_quality', models.IntegerField(blank=True, null=True, verbose_name='Inhaltsqualität')),
                ('satisfaction_content_freshness', models.IntegerField(blank=True, null=True, verbose_name='Aktualität Inhalte')),
                ('weekly_hours', models.FloatField(blank=True, null=True, verbose_name='Stunden/Woche')),
                ('promotes_online', models.BooleanField(blank=True, null=True, verbose_name='Bewirbt online')),
                ('free_text_positive', models.TextField(blank=True, default='', verbose_name='Was gefällt')),
                ('free_text_improvement', models.TextField(blank=True, default='', verbose_name='Verbesserungspotenzial')),
                ('respondent_email', models.CharField(blank=True, default='', max_length=300)),
                ('respondent_name', models.CharField(blank=True, default='', max_length=300)),
                ('limesurvey_response_id', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_snapshots', to='accounts.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Umfrage-Snapshot',
                'verbose_name_plural': 'Umfrage-Snapshots',
                'ordering': ['year'],
                'unique_together': {('account', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SurveyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=300, verbose_name='Feature')),
                ('kind', models.CharField(choices=[('request', 'Feature-Wunsch'), ('not_used', 'Bekannt, aber ungenutzt')], max_length=10)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='accounts.surveysnapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Survey-Feature',
                'ordering': ['feature_name'],
            },
        ),
    ]
