# Generated by Django 6.0.2 on 2026-02-27 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_surveysnapshot_surveyfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionHealthUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('rows_total', models.IntegerField(verbose_name='Zeilen gesamt')),
                ('rows_matched', models.IntegerField(verbose_name='Zeilen gematchet')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Region-Health-Upload',
                'verbose_name_plural': 'Region-Health-Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionHealthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=300, verbose_name='Region (CSV)')),
                ('broken_links', models.IntegerField(verbose_name='Fehlerhafte Links')),
                ('hix_low_count', models.IntegerField(verbose_name='Seiten mit niedrigem HIX')),
                ('total_pages', models.IntegerField(verbose_name='Seiten gesamt')),
                ('missing_translation_pages', models.IntegerField(verbose_name='Seiten mit fehlenden Übersetzungen')),
                ('outdated_pages', models.IntegerField(verbose_name='Veraltete Seiten')),
                ('mt_budget', models.IntegerField(verbose_name='MT Budget')),
                ('active_languages', models.IntegerField(verbose_name='Aktive Sprachen')),
                ('ampel_score', models.FloatField(verbose_name='Ampel-Score')),
                ('ampel_color', models.CharField(choices=[('green', 'Grün'), ('yellow', 'Gelb'), ('red', 'Rot')], max_length=10, verbose_name='Ampelfarbe')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_health_entries', to='accounts.account', verbose_name='Account')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.regionhealthupload', verbose_name='Upload')),
            ],
            options={
                'verbose_name': 'Region-Health-Eintrag',
                'verbose_name_plural': 'Region-Health-Einträge',
                'ordering': ['-upload__uploaded_at', 'region_name'],
            },
        ),
    ]
