# Generated by Django 6.0.1 on 2026-03-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_region_health_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Hauptansprechperson'),
        ),
    ]
