# Generated by Django 4.2.29 on 2026-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_todo_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='anrede',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Anrede'),
        ),
    ]
