# Generated by Django 4.2.29 on 2026-05-01 09:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='campaign_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Anhang')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Erfolgreich')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account-Kampagne',
                'verbose_name_plural': 'Account-Kampagnen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kampagne',
                'verbose_name_plural': 'Kampagnen',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=300, verbose_name='Name')),
                ('contact_salutation', models.CharField(blank=True, default='', max_length=200, verbose_name='Anrede')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('account_name', models.CharField(max_length=300, verbose_name='Account')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='Account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='campaigns.campaign', verbose_name='Kampagne')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact', verbose_name='Kontakt')),
            ],
            options={
                'verbose_name': 'Kampagnen-Kontakt',
                'verbose_name_plural': 'Kampagnen-Kontakte',
                'ordering': ['account_name', 'contact_name'],
            },
        ),
    ]
