# Generated by Django 6.0.1 on 2026-01-30 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_activity_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Kampagne',
                'verbose_name_plural': 'Kampagnen',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=300, verbose_name='Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('account_name', models.CharField(max_length=300, verbose_name='Account')),
                ('bundesland', models.CharField(blank=True, max_length=2, verbose_name='Bundesland')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='Account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='campaigns.campaign', verbose_name='Kampagne')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact', verbose_name='Kontakt')),
            ],
            options={
                'verbose_name': 'Kampagnen-Kontakt',
                'verbose_name_plural': 'Kampagnen-Kontakte',
                'ordering': ['account_name', 'contact_name'],
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
