# Generated by Django 6.0.2 on 2026-02-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
    ]
