# Generated by Django 4.2.29 on 2026-05-01 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
        ('products', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='products.product', verbose_name='Produkt'),
        ),
        migrations.AddField(
            model_name='accountcampaign',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_campaigns', to='accounts.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='accountcampaign',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_campaign_links', to='campaigns.campaign', verbose_name='Kampagne'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncontact',
            unique_together={('campaign', 'contact')},
        ),
    ]
