# Generated by Django 6.0.1 on 2026-02-07 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_task_activities'),
        ('campaigns', '0002_add_campaign_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='campaign_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Anhang')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Erfolgreich')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_campaigns', to='accounts.account', verbose_name='Account')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_campaign_links', to='campaigns.campaign', verbose_name='Kampagne')),
            ],
            options={
                'verbose_name': 'Account-Kampagne',
                'verbose_name_plural': 'Account-Kampagnen',
                'ordering': ['-created_at'],
            },
        ),
    ]
