# Generated by Django 4.2.29 on 2026-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='contact_salutation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Anrede'),
        ),
    ]
