# Generated by Django 4.2.29 on 2026-05-01 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_final_phase', models.BooleanField(default=False, verbose_name='Endphase (Aktiv/Verloren/Beendet)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Produktphase',
                'verbose_name_plural': 'Produktphasen',
                'ordering': ['product', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('field_type', models.CharField(choices=[('date', 'Datum'), ('integer', 'Ganzzahl'), ('boolean', 'Ja/Nein')], max_length=10, verbose_name='Feldtyp')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('show_on_dashboard', models.BooleanField(default=True, verbose_name='Im Dashboard anzeigen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Produktfeld',
                'verbose_name_plural': 'Produktfelder',
                'ordering': ['product', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Beendet zum')),
                ('ended_reason', models.CharField(blank=True, choices=[('price', 'Preis'), ('competitor', 'Wechsel zu Wettbewerber'), ('performance', 'Leistung nicht gepasst'), ('internal', 'Interner Grund beim Partner'), ('other', 'Sonstiges (bitte Notiz schreiben)')], max_length=20, null=True, verbose_name='Beendigungsgrund')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_products', to='accounts.account', verbose_name='Account')),
                ('current_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productphase', verbose_name='Aktuelle Phase')),
                ('lead_account_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_products', to='products.accountproduct', verbose_name='Leit-Account-Produkt (Produktverbund)')),
                ('primary_contacts', models.ManyToManyField(blank=True, related_name='primary_for_products', to='accounts.contact', verbose_name='Hauptansprechpersonen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_products', to='products.product', verbose_name='Produkt')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_products', to=settings.AUTH_USER_MODEL, verbose_name='Verantwortlicher')),
            ],
            options={
                'verbose_name': 'Account-Produkt',
                'verbose_name_plural': 'Account-Produkte',
                'unique_together': {('account', 'product')},
            },
        ),
        migrations.CreateModel(
            name='AccountProductFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, default='', max_length=500)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('account_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='products.accountproduct', verbose_name='Account-Produkt')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productfield', verbose_name='Feld')),
            ],
            options={
                'verbose_name': 'Feldwert',
                'verbose_name_plural': 'Feldwerte',
                'unique_together': {('account_product', 'field')},
            },
        ),
    ]
