# Generated by Django 6.0.1 on 2026-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfield',
            name='show_on_dashboard',
            field=models.BooleanField(default=True, verbose_name='Im Dashboard anzeigen'),
        ),
    ]
