# Generated by Django 6.0.1 on 2026-02-04 08:41

from django.db import migrations


def rename_gewonnen_to_abgeschlossen(apps, schema_editor):
    ProductPhase = apps.get_model('products', 'ProductPhase')
    ProductPhase.objects.filter(name='Gewonnen').update(name='Abgeschlossen')


def rename_abgeschlossen_to_gewonnen(apps, schema_editor):
    ProductPhase = apps.get_model('products', 'ProductPhase')
    ProductPhase.objects.filter(name='Abgeschlossen').update(name='Gewonnen')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productfield_show_on_dashboard'),
    ]

    operations = [
        migrations.RunPython(rename_gewonnen_to_abgeschlossen, rename_abgeschlossen_to_gewonnen),
    ]
