# Generated by Django 6.0.2 on 2026-02-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_seed_integreat_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphase',
            name='is_final_phase',
            field=models.BooleanField(default=False, verbose_name='Endphase (Abgeschlossen/Verloren)'),
        ),
    ]
