# Generated by Django 6.0.1 on 2026-03-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_accountproduct_primary_contact'),
        ('products', '0007_accountproduct_lead_account_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproduct',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_products', to='accounts.contact', verbose_name='Hauptansprechperson'),
        ),
    ]
