# Generated by Django 4.2.29 on 2026-03-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_todo_assigned_to'),
        ('products', '0010_beendet_phase_and_ended_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountproduct',
            unique_together={('account', 'product')},
        ),
    ]
